### ISSUE TITLE
Border incorrect in progress control

### ISSUE THREAD

**Issue by Cacowned** [ossw/ossw-android#1]
In WatchSetCompiler.java method compileProgressControl, the border property is incorrectly retrieved from the size object instead of the style object.

However, after fixing that, I still see no border when uploading the watchset to my watch (nor does the Renderer in the app show the border)

**Comment by Cacowned** [comment]
I swapped the lines putting the border in the stream, first a 0, then the border value, and then it correctly shows a border on my watch.

**Comment by althink** [comment]
Fixed in 0.4.0 (also in the android app because border was not rendered at all)
