### ISSUE TITLE
Settings/Alarm Notif. or Notif. / Active time interval

### ISSUE THREAD

**Issue by zigastegu** [ossw/ossw-android#31]
- change default to whole day 00:00-23:59 (best to have all day, new user defines smaller)
- Change input method to the one used by alarm clock, current number input does not allow ":" in my case CM11, 4.4.4, have to copy and paste from another app, to change after accidentally remove
- validate input (second setting must be after first setting)

**Comment by vaspa** [comment]
Hope the latest update improves the usability.
As for the validation, in my opinion we should leave a possibility to define any intervals, e.g. 13:00-02:00. It can be useful for someone with unusual timetable.
