### ISSUE TITLE
Reposition the Notif. ON/OFF to main Settings screen

### ISSUE THREAD

**Issue by zigastegu** [ossw/ossw-android#32]
If possible reposition the ON/OFF from inside notifications to main Settings screen. I new case state of notifications is clearer. Maybe even add time interval as a reference below

![notif_on_off](https://cloud.githubusercontent.com/assets/1379063/11919822/e6393984-a75c-11e5-9948-366e8a636b55.png)

![main_settings_new](https://cloud.githubusercontent.com/assets/1379063/11919853/c04db398-a75d-11e5-918a-487ee46553dc.png)

**Comment by vaspa** [comment]
This switch implementation has no "clean" solution but can be implemented with a little bit of hacking.
BTW the time interval concerns the vibration only, the notification itself is always pushed to the watch (if  not filtered).
