### ISSUE TITLE
Add vibration pattern settings for notifications

### ISSUE THREAD

**Issue by vaspa** [ossw/ossw-android#9]
Feature added, but needs testing. Inconsistent behavior for now.

**Comment by althink** [comment]
I've fixed the way vibration pattern is built, you had some bad assumptions:
- First part of pattern (X << 26) is not a number of repeats but number of steps in pattern. So if you have 110010 pattern then X = 6.
- Pattern has to be left aligned so for pattern 110010 right part should be: 1100100000000000

**Comment by althink** [comment]
Pattern preview still has to be fixed because empty notification data is not expected by the watch and it shows random garbage from memory.

**Comment by althink** [comment]
I've removed number of repeats in alert notification because it vibrates as long as this alert is valid so until you answer/reject the phone call or dismiss alarm.

**Comment by althink** [comment]
Both notification/alert preview should now work fine

**Comment by vaspa** [comment]
Ok, now I have an alert preview, but a couple of problems.
- No notification message/no vibration on the watch (only the message in the notification bar on the phone).
- The alert test is very short. I even don't get if there is some pattern in vibration or not.

**Comment by althink** [comment]
So it means that there is some generic problem with alerts on your android version that has to be fixed. On my 5.1.1 when you click "Test alert notifications" watch starts to vibrate and shows "Test alert" and it stops only when "Close" action is invoked on watch or phone. I will check tomorrow on 4.4.X phone.

**Comment by vaspa** [comment]
Ok, then. I'll put CM12.1 on another Galaxy i9100 and will test it in the following days.

As far as the "steps" number means the pattern length we can remove the "repeat" field completely deducing the length from the given pattern string.
The duration is for the whole pattern or for each step?

**Comment by althink** [comment]
Steps are counted from pattern length. Repeat is used to calculate total vibration length so when repeat is set to 3 total vibration time is set to 3 \* pattern duration so pattern is repeated 3 times. Duration parameter in app is a total duration of one pattern. In binary format duration means step duration so I divide duration set in app by pattern length.

**Comment by vaspa** [comment]
Clear for duration parameter.

As for the repeat field -- I added it because of misunderstanding of the step count parameter.
Ok, I see the "timeout" parameter that was 1200 earlier. Do I understand correctly that it is the "total duration" and the watch will repeat the vibration until "timeout" happens?
I'd rather remove the "repeat" for simplicity because 16 bits is sufficient to create lots of different patterns.
What do you think? Do you want to keep it?

**Comment by althink** [comment]
Yes, this "timeout" is a total duration of the vibration so when pattern is shorter than timeout then it's repeated. Originally it was used for alert notifications where default timeout is I think about 7 seconds and if connection between phone and watch will break it will not vibrate infinitely. And every 1,5 seconds phone extends this timeout.

I would like to leave it ("repeat") for now because I'm using it ;) If there will be to many parameters on notification settings screen then we can always extract those three parameters (repeat, pattern and duration) to separate screen or a popup.

**Comment by vaspa** [comment]
Great! Last status:
I have only "real" notifications, like e-mail, working on KitKat.
The preview doesn't work for notifications, the alert blinks on the screen (~200-300ms) and disappears.

Offtopic:
Just to be more efficient. Could you tell me if you'll work on finding a fix or I'll tackle this problem?
A little planning for the next few features, maybe? What are the priorities for you? 
I wanted to work several days on the app+UI: drawer, status bar, notifications filter, disconnection alert...
My resources: 1-2 hours per day, and its my first Android app.  :)

**Comment by althink** [comment]
I'll try to fix notifications on android 4.4.2, my girlfriend has it so it's easier ;) And yes, it's definitely broken. I've tested it earlier on 4.4.4 (both cyanogenmod and android emulator) and it behaved completely different than this 4.4.2 HTC version :/

I want to focus on possibility to upload multiple watchsets, browse watch filesystem in the app and allow to override every default screen with a watchset. So if you will focus on android part UI then that's great.

**Comment by althink** [comment]
Notification preview should work now on 4.4.2

**Comment by althink** [comment]
I've changed a bit android app code to separate watch faces, applications and utility screens. After upload they are kept in different folders on the watch. 

There are some navigation changes. Now multiple files may be uploaded and custom watch face is integrated with other screens. On watch face screen you can press:

long up: list uploaded watchfaces, press select to choose one as default
long down: list utility files, nothing for now but here will be files that overrides settings screen, notification screen, device info screen etc
long select: options as in previous versions
short select: list of applications, short press select to run

short up and short down currently do nothing, I thing the best option is to allow to assign applications to those buttons so they will work as shortcuts

Lastast firmware snapshot: https://www.dropbox.com/s/1pgmqvhhml2nff2/ossw-firmware-s120-0.5.0-snapshot.zip?dl=0
